"""Write `docs/system_prompt_full.md`: the system prompt exactly as the model gets it.

    python scripts/rehla/dump_system_prompt.py

A review copy, never read by the app. Rendered against a throwaway SQLite
database seeded the way boot seeds one (`_ensure_catalog_seeded`,
`_ensure_shipping_fees_set`), so the shipping sentence is the one production
says with the published fees -- the dump of 1d7ee38 was rendered against a
test fixture that priced only Cairo, and showed «60 جنيه لكل محافظات مصر».
No Shopify, no Meta, no model call: nothing here needs a credential.
"""

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
os.chdir(REPO)

for name in (
    "SHOPIFY_STORE_DOMAIN", "SHOPIFY_ADMIN_TOKEN", "SHOPIFY_WEBHOOK_SECRET", "SHOPIFY_API_SECRET",
    "INSTAGRAM_ACCESS_TOKEN", "INSTAGRAM_ACCOUNT_ID", "INSTAGRAM_APP_SECRET",
    "WHATSAPP_ACCESS_TOKEN", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_APP_SECRET",
):
    os.environ[name] = ""
_DB = Path(tempfile.gettempdir()) / "rehla_prompt_dump.db"
_DB.unlink(missing_ok=True)
os.environ["DATABASE_URL"] = f"sqlite:///{_DB.as_posix()}"
os.environ["LOCAL_STORE"] = "1"

OUT = REPO / "docs" / "system_prompt_full.md"

HEADER = """# Rehla — full system prompt (as the model receives it)

Generated by `python scripts/rehla/dump_system_prompt.py` against a database
seeded the way boot seeds one (Cairo/Giza {cairo} EGP, elsewhere {other} EGP).
**Review copy only — editing this file changes nothing.** No secrets: the
prompt contains none. The audit that produced this version is
`docs/prompt_review.md`.

Representative context: WhatsApp, returning customer whose saved name is
«{name}», writing Arabic.

## Where each part comes from

| Part | Source |
|---|---|
| Body (persona, rules, purchase flow, orders, return & exchange policy, handoff) | `assistant/prompt.py::_TEMPLATE`, filled by `render()` |
| Shipping line, delivery days, payment line, example fee/total | `domain/services/shop_facts.py` (`shipping_line` reads the `shipping_rates` table, `delivery_line`, `PAYMENT_LINE`, `example_fee`); example price `prompt._EXAMPLE_PRICE` (Rehla Tops) |
| Exchange/return days | `shop_facts.EXCHANGE_DAYS` / `RETURN_DAYS` |
| Surface line (WhatsApp vs Instagram) and Instagram paragraph | `assistant/prompt.py::build_system_prompt` |
| Customer-name note (appended per turn) | `assistant/customer_name.py::turn_note` |
| Reply-language note (appended per turn) | `assistant/reply_language.py::turn_note` |
| Conditional, not shown here: resume paragraph after a crash | `assistant/recovery.py::RESUME_INSTRUCTION` via `system_extra` |
| Conditional, not shown here: undelivered-photo note, retry nudges (truncation, offer, action, handoff, change, blame, accepted offer, rule) | `assistant/agent.py` (`_UNDELIVERED_NOTE`, `_*_NUDGE`, `_ACTION_NUDGE`, `_RULE_NUDGE`) |

The catalog is **not** injected into the prompt: products, prices, stock and
size charts reach the model only through tool results. Tools offered:
{tools}.

Size: {size} characters (WhatsApp body, before the per-turn notes).

## WhatsApp prompt (verbatim)

````text
{whatsapp}
````

## Instagram difference

An Instagram DM turn swaps the surface line for «{ig_line}» and appends:

````text
{ig_paragraph}
````
"""


def main() -> int:
    import app as app_module
    from assistant import customer_name, reply_language
    from assistant.prompt import _INSTAGRAM_PARAGRAPH, INSTAGRAM_SURFACE_LINE, build_system_prompt
    from assistant.tools.base import REGISTRY
    from domain.db import engine, session_scope
    from domain.models import Base
    from domain.services import shop_facts

    Base.metadata.create_all(engine)
    app_module._ensure_schema_columns()
    app_module._ensure_catalog_seeded()
    app_module._ensure_shipping_fees_set()

    name = "منة"
    with session_scope() as db:
        body = build_system_prompt(session=db)
        whatsapp = body + customer_name._KNOWN_NOTE.format(name=name) + reply_language.turn_note("ar")

    OUT.write_text(
        HEADER.format(
            cairo=shop_facts.fee_for("Cairo"),
            other=shop_facts.DEFAULT_SHIPPING_FEE,
            name=name,
            tools=", ".join(sorted(REGISTRY)),
            size=len(body),
            whatsapp=whatsapp,
            ig_line=INSTAGRAM_SURFACE_LINE,
            ig_paragraph=_INSTAGRAM_PARAGRAPH,
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUT.relative_to(REPO)} ({len(body)} chars)")
    engine.dispose()
    _DB.unlink(missing_ok=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
